---
- name: Generate or update alertmanager config.
  become: true
  ansible.builtin.copy:
    src: alertmanager-config.yml
    dest: "{{ appdata_path }}/{{ item.name }}/config.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0664
  notify: Restart alertmanager
