---
- name: Create or update directory for {{ item.name }}.
  become: true
  ansible.builtin.file:
    path: "{{ appdata_path }}/{{ item.name }}"
    state: directory
    owner: "{{ path_file_owner }}"
    group: "{{ path_file_group }}"
    mode: "{{ path_mode }}"
  with_items: "{{ containers }}"
  when: item.enabled

- name: Include homer tasks.
  ansible.builtin.include_tasks: homer.yml
  with_items: "{{ containers }}"
  when: item.name == "homer" and item.enabled

- name: Include qbittorrent-vpn tasks.
  ansible.builtin.include_tasks: qbittorrent-vpn.yml
  with_items: "{{ containers }}"
  when: item.name == "qbittorrent-vpn" and item.enabled

- name: Generate or update docker-compose file.
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_path }}/docker-compose.yml"
    owner: "{{ path_file_owner }}"
    group: "{{ path_file_group }}"
    mode: "{{ file_mode }}"
  notify: Restart docker compose
