---
- name: Create or update prometheus config directory.
  become: true
  ansible.builtin.file:
    path: "{{ appdata_path }}/{{ item.name }}/config"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Create or update prometheus data directory.
  become: true
  ansible.builtin.file:
    path: "{{ appdata_path }}/{{ item.name }}/data"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Generate or update prometheus config.
  become: true
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ appdata_path }}/{{ item.name }}/config/prometheus.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0664
  notify: Restart prometheus

- name: Generate or update prometheus alert rules.
  become: true
  ansible.builtin.copy:
    src: alert.rules
    dest: "{{ appdata_path }}/{{ item.name }}/config/alert.rules"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0664
  notify: Restart prometheus
