---
- name: Generate or update renovate config.
  become: true
  ansible.builtin.template:
    src: renovate.json.j2
    dest: "{{ appdata_path }}/{{ item.name }}/config.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0664
  notify: Restart renovate
