---
collections:
  - name: community.sops
    version: 1.9.1
  - name: devsec.hardening
    version: 10.1.0
  - name: ansible.posix
    version: 1.6.2

roles:
  - name: geerlingguy.ntp
    version: 2.5.0
  - name: geerlingguy.docker
    version: 7.4.3
  - src: artis3n.tailscale
    version: v4.5.0
