---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/provision/ansible"

includes:
  ansible: .taskfiles/AnsibleTasks.yml
  precommit: .taskfiles/PrecommitTasks.yml
  sops: .taskfiles/SopsTasks.yml
