---
compose_path: /srv
appdata_path: "{{ compose_path }}"
docker_up_command: docker compose pull && docker compose down --remove-orphans && docker compose rm && docker compose up -d
docker_update_command: docker compose pull && docker compose down --remove-orphans && docker compose rm && docker compose up -d
docker_cleanup_command: docker image prune -f && docker volume prune -f

global_env_vars:
  - PUID={{ current_user.uid }}
  - PGID={{ current_user.uid }}
  - TZ=Europe/Vienna

containers:
  - name: flame
    enabled_on: docker
    image: pawelmalak/flame:2.3.1@sha256:ed331453caf5ad167b8cc4c6d03d855e7a1d11e7387aa7c4c312cf0680dbe601
    volumes:
      - "{{ appdata_path }}/flame:/app/data"
    ports:
      - 5005:5005
    environment:
      - PASSWORD={{ secret_flame_password }}
    mem_limit: 128m

  - name: qbittorrent
    enabled_on: docker
    image: ghcr.io/hotio/qbittorrent:release-4.6.4@sha256:39829b3e092a91fb15f6696d5a8b762a2da6436ff59e529e13305e6bfb52f829
    ports:
      - 8080:8080
      - 8118:8118
    environment:
      - UMASK=022
      - VPN_ENABLED=true
      - VPN_LAN_NETWORK={{ secret_wireguard_lan_network }}
      - VPN_CONF=wg0
      - VPN_ADDITIONAL_PORTS
      - VPN_IP_CHECK_DELAY=5
      - VPN_IP_CHECK_EXIT=true
      - PRIVOXY_ENABLED=false
    volumes:
      - "{{ appdata_path }}/qbittorrent:/config"
      - /mnt/data/torrents:/data/torrents
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    mem_limit: 4096m

  - name: radarr
    enabled_on: docker
    image: lscr.io/linuxserver/radarr:5.15.1@sha256:c60610599d681dc7ea0aa1a5edfc1637ff4b5fb062872aea1539d291c835c4b3
    volumes:
      - "{{ appdata_path }}/radarr:/config"
      - /mnt/data:/data
    ports:
      - 7878:7878
    mem_limit: 512m

  - name: sonarr
    enabled_on: docker
    image: lscr.io/linuxserver/sonarr:4.0.10@sha256:a30d870ae503e617e84909367c8f19096567ef60834fa8d81d86d17a13e50d1a
    volumes:
      - "{{ appdata_path }}/sonarr:/config"
      - /mnt/data:/data
    ports:
      - 8989:8989
    mem_limit: 512m

  - name: sonarr-anime
    enabled_on: docker
    image: lscr.io/linuxserver/sonarr:4.0.10@sha256:a30d870ae503e617e84909367c8f19096567ef60834fa8d81d86d17a13e50d1a
    volumes:
      - "{{ appdata_path }}/sonarr-anime:/config"
      - /mnt/data:/data
    ports:
      - 9898:8989
    mem_limit: 4096m

  - name: prowlarr
    enabled_on: docker
    image: lscr.io/linuxserver/prowlarr:1.27.0-develop@sha256:006b7c8f63312b22e7d8a456cc210c114555d7f0e3570a4ac84d7b79819c8cff
    volumes:
      - "{{ appdata_path }}/prowlarr:/config"
    ports:
      - 9696:9696
    mem_limit: 1024m

  - name: recyclarr
    enabled_on: docker
    image: ghcr.io/recyclarr/recyclarr:7.4.0@sha256:619c3b8920a179f2c578acd0f54e9a068f57c049aff840469eed66e93a4be2cf
    volumes:
      - "{{ appdata_path }}/recyclarr:/config"
    mem_limit: 128m

  - name: sabnzbd
    enabled_on: docker
    image: lscr.io/linuxserver/sabnzbd:4.3.3@sha256:cf7743af338e1cdfc97f6e6c605c8c45d737a4f268ab96ba6cec565134cea5e1
    ports:
      - 8082:8080
    volumes:
      - "{{ appdata_path }}/sabnzbd:/config"
      - /mnt/data/usenet:/data/usenet
    mem_limit: 8192m

  - name: tautulli
    enabled_on: docker
    image: lscr.io/linuxserver/tautulli:2.15.0@sha256:b2a2a615485103eb1e2b10bd0e29088be36b827495a643e433249c5dc945f1e6
    ports:
      - 8181:8181
    volumes:
      - "{{ appdata_path }}/tautulli:/config"
    mem_limit: 512m

  - name: plex
    enabled_on: docker
    image: ghcr.io/linuxserver/plex:1.41.2@sha256:a3a3a850a64fb747c59f85dbc19b157781c3b9c921a83799127894b0ebdf3a68
    environment:
      - VERSION=docker
      - DOCKER_MODS=linuxserver/mods:plex-absolute-hama
    ports:
      - 32400:32400
    volumes:
      - "{{ appdata_path }}/plex:/config"
      - /mnt/data/media:/data/media
      - /tmp/plex:/transcode
    devices:
      - /dev/dri:/dev/dri
    mem_limit: 8192m

  - name: overseerr
    enabled_on: docker
    image: lscr.io/linuxserver/overseerr:1.33.2@sha256:51cc0140a896591aee450170c9cf7af07a8a282cc43b8db8396f93186ab54425
    volumes:
      - "{{ appdata_path }}/overseerr:/config"
    ports:
      - 5055:5055
    mem_limit: 512m
