secret_wireguard_conf: ENC[AES256_GCM,data:IAYzD6q7vj4R4pUspdS0j0fBFXHXaaD4qg+fQBbwDryPt9gJTfAEtZ1m2NyZLX9QuJAjyXxFxsT6ydAn43wHjy3O7sofjWsxW9CXiiTsIzKF5HoNYt5iz5VHLbuD9jWFtazfzIGiKj7quIGPgR5/rgYWfsWdiICgn+rfd11tpyMX+aywz4tBOqvmKgz+otkmpWdBcSWB2QqtfQkFiiX/97gYn5tGEbUs+IMjoRvF8mlHdJEqyEQG9hXabVxDo1Tx9eErTX5UVn26sPy7+ULQ748s8hWhx/DIqceNL+kC1CJK7w6jaPjH,iv:C3E98iKxp/qdyvto+C5etGizuix36/H8BDkkG6zsTIQ=,tag:FFMrz8o25eySvOXYr4ejpw==,type:str]
secret_wireguard_lan_network: ENC[AES256_GCM,data:is/xYWYgJ41hkrjY7mnB,iv:HrJvzuZ/3P4OVGQwD0aI3X/pwl58E3zSFGPFWr43Zao=,tag:owGyEIKKCYtuzBJluPSkmQ==,type:str]
secret_alertmanager_discord_webhook: ENC[AES256_GCM,data:bb90S0D5RhKSQbDn38MrF3JujYGNdI83sPoq8bOz+wTRGq7H6TYfXJoVMysd2S2wmBk/xSGAdGjOuIqzdohquNRq6XDNtOR1RZ1kwLOc8rePqK2CWV0bb9ScWwu5Xwe0W5P79j7Q4dpkS6d4TOsrnysHjwUT5uYl5Q==,iv:TaABLJQxETRYEOeGUmPddyK6dYvqtrGW47fM8/p4+ms=,tag:EYLkPPzXQ5h60PLQCLRViw==,type:str]
secret_flame_password: ENC[AES256_GCM,data:eLJUwS9WDqFjAiePr37hZFlIQVnVP7YlcRcJHQuOEQg=,iv:xYgUqBdBCxrfHADRFM3qLajazrFq2xFem7aMMV/hji8=,tag:WU+vX+WZiIpOH+Mz3tZ99g==,type:str]
secret_radarr_api_key: ENC[AES256_GCM,data:jyTcb0VFOVnxs1qk1C7AiL5ooLhRtfVc9lIVq5QXQo0=,iv:E2BDlI7w1L3IzwCpdrnISefqgQlEshe0wSJX4UwLyaI=,tag:N1sWmY1lM6Dk6xLh3Q9nkw==,type:str]
secret_sonarr_api_key: ENC[AES256_GCM,data:ww1X07CiVG05I85b632UA4YCyxVU0zS1TjIeWxBD2RM=,iv:UHsdrAhw4oDhTFah9zPWTuQRq1w9B5F+b38HpWRnpFQ=,tag:73scbWoyIriA+GY3lfWybg==,type:str]
secret_renovate_token: ENC[AES256_GCM,data:3Tt0s3rdVe4fKDsGT9HfVAtQWdhtGi/5AmToT+kJPYmu+nNFNQAjLg==,iv:UcmeKVKAMrRVjyXBE2glRmNJQo4OyBUzK8mio6ewXc8=,tag:AUXTOIvCXvjA7HfO1/H5lQ==,type:str]
secret_fireflyiii_app_key: ENC[AES256_GCM,data:k0VcKfmJTrOEux1TxZsx8nKDu0CCXKzyrX7tSX2rFx0=,iv:6e3WboTsKqR5B11Z4xkFJGKKivB5/5n1y1UfEeHJUPk=,tag:oerSUuPyQjrnIpLPKwYXkw==,type:str]
secret_postgres_fireflyiii_password: ENC[AES256_GCM,data:BqrQgmbik/xglk2xhnck+KJ8i54qBYf996QLfDGK5UA=,iv:qRYudcHfaNUND30K+J+BPEv17UwIaakTywfglufzVkE=,tag:k3DpykFuC8YzFQbq/4pt3g==,type:str]
secret_postgres_vikunja_password: ENC[AES256_GCM,data:a9qnE7htBIpbVZ4Vbgcb0tzcs4TRqq655OtJlAJ+li4=,iv:48wEbEmcSlfsdxBcUku7V/qm50BE0ET84NlI6XP9TzA=,tag:s8JiODTJJxnJViKOKEYKFA==,type:str]
secret_postgres_miniflux_password: ENC[AES256_GCM,data:KdfbaYqwe52jAOtFp0FOExw7KSzyO6gXbyAo2xcpfHQ=,iv:t01I7XL8Og9PxYFJ/N7bhMP0ltwQay6qkuLGHajD008=,tag:f5WEA0n+ymq9iGWevs+fHA==,type:str]
secret_miniflux_admin_password: ENC[AES256_GCM,data:zCfuYnP+EiFe2+IR/mf+XXQcaLL2TNLgzTROsIgQL4w=,iv:PLG4q5EyeSbY14Ek+Nrdw68wtt3uFFesGH62ZDx4w9k=,tag:KIhoqFI7sVVuk5Ac4l/NDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh8m8zxpvxmj90s4x6hjhd7u5t35gy94knsq5u53gukavpd42qvsg02yfl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcUN4ZzV0c0gwaVVML0JO
            SVRsSWpSUHQwY0JjMXQ2VjYyZldoaStYT0JzCm9QQ25sODhIdlBmRlk4MlNMU1Zt
            bjBSWkRjbFJRd24vZHI2Nk1NVHFvekUKLS0tIEtoYWpwOWprLzNwMzFaaWZOZ1Bv
            U3pPQ0E2VUFBWlhYUkh6K0UwMVlJVVUKpAfOUM7/lqXCoOrrXWXJdTPT4jvEd8+q
            UB/u61Pqa5MMeo5z7kZW2+jfRyeQ6lQ6vQJhoIFqtQcO1DBhoBGsmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-14T14:29:18Z"
    mac: ENC[AES256_GCM,data:euYbTBw5XW2LrfKkvEKiwzzsTcRYUanYyFVV5lhuiphxy2M3RaDXX+TOTVV1wCTkWzVgSskOuFuS9cjOQ9h8BKsKBsGkKEfNllkcIhlYI4ZibvrLpsxiXpKe+niL22R0THX4XTZvV3RYDN8xwxN9RsQg4+hwiEluwNxUnkYSy0c=,iv:ibKWY61rpBBB5HSW0tC9GSC9JHbMneSTxdBKi7AmeA0=,tag:DNd8Y4+Uvyt8bHIXg7wdRg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
