secret_wireguard_conf: ENC[AES256_GCM,data:7hU5PgIgbq5CtinwbuXsmnAXbHXhrhzknCnxgY5q/3I6cpKQaZtoBPbWRfFAw555xfKaS8rIqIRrEq+ukA7lFHygz2l2oyHiDLsS335B1eA795sYwvPCcoQgNPPpQJMvhfnyhfQoBXo8rUxaXGw9FYm1G2vBIgvbT4uWLXTO5eN9OT9w6aJKgNVQ2802fVutby2Er45vACsfJx7Jvj+ijsNaB0WQW59xOk9Unzm+Jf4g+SdPIwzYzpm/9JH2TvOmEiVqdzplDzfazQxqS+ylojqbCT+xLimfuIftrkz1jHClBy+8RjEL,iv:bJC8/ACuKtedY2xX6K/PXe3HAfiIqSLifHXTmoarf+o=,tag:lTA+yzrt8aYWmqXhKWMS2g==,type:str]
secret_wireguard_lan_network: ENC[AES256_GCM,data:O2xj/Iq5v19uX03cv7Mb,iv:l5Hcof4JFpdGdyVA8Tei9p4WkfzBu32f5oWQsVlKp6k=,tag:HTu7HzHyLRoGdqi9lmAIgw==,type:str]
secret_alertmanager_discord_webhook: ENC[AES256_GCM,data:m50Yl4tfFAHuaqF6AcgEE+2TBzsP1UIBEBWqfX3FF5VvN6xk0Lc7hRXl1W2I/x45KTjajQFf/F0Hfs8P1j9NSEfmOxujyLWpjYW27JUgwxiIpOCzmJ9MwXnEzZJ9ImEnvyPbxOGSE6+RGcBHFo40Cu8qdNOPiDAVmQ==,iv:Gu4zo/zun72XKNxSQVVkmWMhwg0ZLZ3JjhjDPmvD7Ww=,tag:85GcXgDUcbHWdjqHdeJY+Q==,type:str]
secret_flame_password: ENC[AES256_GCM,data:G9swEx1yHE+adeuOeq3hJzC2+fzMI0LnH33yyMMFBEg=,iv:sTLKRIC0Vurul8/I7HPS/Qm2Zb9yeL9HEkUU7mVJKew=,tag:DDB+MB+6eh1DKZmkDvmftA==,type:str]
secret_radarr_api_key: ENC[AES256_GCM,data:YGxeyx9z9xQGwT/mYSOJjqQlUe6Srm+yq+hLHZSsSJ4=,iv:y0s+FBeXT7KmDJ5AiixyfHEFZs4ZzoVk097rhWpIm7s=,tag:xb5AmOdGVK0rm9ARdqyLDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh8m8zxpvxmj90s4x6hjhd7u5t35gy94knsq5u53gukavpd42qvsg02yfl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NmFjK0NuQTZscWdlRG5D
            aHkyOUY1aUptVTlnTUczVVJTNFRBanVHNEY0Cnl2eHZVN2h5ZEE4VGxESFRkaHBE
            QWZSL0hwQUgrWHEydHNoM0dEQ2Z3RUUKLS0tIEVtVW9pTDJuK2xPSXZpSFVEa1Qz
            RVgyQ2tDZmNKdWhlUlh0eVB6U3kyWXcKddHnmoMOf0UpcHeCklyJEGNnPDKuGnca
            rWRC+iPB+stbZTGK43YWBj94ePN6IijOjWgJVDMw/BOw5ie3iXNJGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-04T18:09:57Z"
    mac: ENC[AES256_GCM,data:JW+ahoZiwweesexd71wlFAmnwMukYIKqx7jdJy6is5/CaIkOEuqVyRqawbcqfAqtgNxBDYf6efKMcaW56foF3ZhsurSf4Ddqye5I2cu2r5RTnd4wH9JAWMFk0b/76NkXvwK991xVJHpn98qWpxGQPWoU5xKM/oHszZEtHSB/yGc=,iv:PMVb1y1MTTVSqaYalFplwPN2AtRlog2klApG3yAaODU=,tag:CLMV13mtNPE+GmaDHIHEGg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
