---
- name: Ensure nfs packages are available.
  become: true
  ansible.builtin.apt:
    name: nfs-common
    state: present

- name: Create or update mount directory.
  become: true
  ansible.builtin.file:
    path: "{{ mount_path }}"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ mode }}"

- name: Mount nfs volume.
  become: true
  ansible.posix.mount:
    src: "{{ mount_src }}"
    path: "{{ mount_path }}"
    opts: "{{ mount_opts }}"
    state: mounted
    fstype: nfs
