---
- name: Start docker compose
  ansible.builtin.shell: # noqa command-instead-of-shell
    chdir: "{{ compose_path }}"
    cmd: "{{ docker_up_command }}"

- name: Restart qbittorrent
  ansible.builtin.command:
    chdir: "{{ compose_path }}"
    cmd: docker compose restart qbittorrent

- name: Restart prometheus
  ansible.builtin.command:
    chdir: "{{ compose_path }}"
    cmd: docker compose restart prometheus

- name: Restart alertmanager
  ansible.builtin.command:
    chdir: "{{ compose_path }}"
    cmd: docker compose restart alertmanager

- name: Restart recyclarr
  ansible.builtin.command:
    chdir: "{{ compose_path }}"
    cmd: docker compose restart recyclarr

- name: Restart renovate
  ansible.builtin.command:
    chdir: "{{ compose_path }}"
    cmd: docker compose restart renovate
