---
- name: Start docker compose
  ansible.builtin.shell: # noqa command-instead-of-shell
    chdir: "{{ compose_path }}"
    cmd: "{{ docker_up_command }}"

- name: Restart qbittorrent
  ansible.builtin.command:
    chdir: "{{ compose_path }}"
    cmd: docker compose restart qbittorrent

- name: Restart recyclarr
  ansible.builtin.command:
    chdir: "{{ compose_path }}"
    cmd: docker compose restart recyclarr
