---
name: Lint

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  # Currently no way to detect automatically
  DEFAULT_BRANCH: main

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - name: MegaLinter
        uses: oxsecurity/megalinter@d8c95fc6f2237031fb9e9322b0f97100168afa6e # v8.2.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          ENABLE_LINTERS: |-
            ${{
              join(
                fromJSON('
                  [
                    "ACTION_ACTIONLINT",
                    "ANSIBLE_ANSIBLE_LINT",
                    "COPYPASTE_JSCPD",
                    "MARKDOWN_MARKDOWNLINT",
                    "REPOSITORY_GIT_DIFF",
                    "REPOSITORY_SECRETLINT",
                    "YAML_PRETTIER",
                    "YAML_YAMLLINT"
                  ]
                '),
                ','
              )
            }}
          ANSIBLE_DIRECTORY: provision/ansible
          ANSIBLE_ANSIBLE_LINT_CONFIG_FILE: .github/linters/.ansible-lint
          MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .github/linters/.markdownlint.yaml
          MARKDOWN_MARKDOWNLINT_RULES_PATH: .github/
          YAML_YAMLLINT_CONFIG_FILE: .github/linters/.yamllint.yaml
          YAML_PRETTIER_CONFIG_FILE: .github/linters/.prettierrc.yaml
          YAML_PRETTIER_FILTER_REGEX_EXCLUDE: "(.*\\.sops\\.ya?ml)"
